# Generated by Django 4.2.28 on 2026-02-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("calories_100g", models.FloatField(help_text="kcal per 100 g")),
                ("protein_100g", models.FloatField(help_text="g per 100 g")),
                ("carbs_100g", models.FloatField(help_text="g per 100 g")),
                ("fat_100g", models.FloatField(help_text="g per 100 g")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("usda", "USDA")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("fdc_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("match", "Match"),
                            ("training", "Training"),
                            ("rest", "Rest"),
                        ],
                        default="training",
                        max_length=10,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("maintain", "Maintain"),
                            ("bulk", "Bulk"),
                            ("cut", "Cut"),
                        ],
                        default="maintain",
                        max_length=10,
                    ),
                ),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("carbs_g", models.FloatField()),
                ("fat_g", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="scout.player",
                    ),
                ),
            ],
        ),
    ]
