# Generated by Django 4.2.28 on 2026-02-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scout", "0002_player_current_club_player_market_value_eur_and_more"),
        ("nutri", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "name",
                    models.CharField(
                        help_text="Supplement product name", max_length=120
                    ),
                ),
                (
                    "dose_mg",
                    models.FloatField(
                        help_text="Dose in mg (or g × 1000 for convenience)"
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("pre_train", "Pre-Training"),
                            ("intra_train", "Intra-Training"),
                            ("post_train", "Post-Training"),
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("with_meal", "With Meal"),
                        ],
                        default="post_train",
                        max_length=20,
                    ),
                ),
                (
                    "batch_tested",
                    models.BooleanField(
                        default=False,
                        help_text="Product certified by Informed Sport, BSCG, or NSF for anti-doping compliance",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Lot / batch number — required for forensic audit in doping investigations",
                        max_length=80,
                    ),
                ),
                (
                    "cert_body",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Certifying body: Informed Sport | BSCG | NSF | Informed Choice | None",
                        max_length=80,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplements",
                        to="scout.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "name"],
            },
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grams", models.FloatField()),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("am_snack", "AM Snack"),
                            ("lunch", "Lunch"),
                            ("pm_snack", "PM Snack"),
                            ("dinner", "Dinner"),
                            ("pre_train", "Pre-Training"),
                            ("post_train", "Post-Training"),
                            ("pre_sleep", "Pre-Sleep"),
                        ],
                        default="breakfast",
                        max_length=20,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("calories", models.FloatField(default=0.0)),
                ("protein_g", models.FloatField(default=0.0)),
                ("carbs_g", models.FloatField(default=0.0)),
                ("fat_g", models.FloatField(default=0.0)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to="nutri.food",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to="nutri.dailyplan",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_time", "logged_at"],
            },
        ),
    ]
