# Generated by Django 4.2.28 on 2026-02-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("CB", "Centre Back"),
                            ("RB", "Right Back"),
                            ("CM", "Central Midfielder"),
                            ("FW", "Forward"),
                        ],
                        max_length=10,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("preferred_foot", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="scout.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yearly salary in EUR",
                        max_digits=14,
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Transfer fee in EUR",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="scout.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatchStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(default="2024-25", max_length=10)),
                ("progressive_passes", models.FloatField(default=0)),
                ("carries", models.FloatField(default=0)),
                ("defensive_actions", models.FloatField(default=0)),
                ("duel_win_rate", models.FloatField(default=0)),
                ("crosses", models.FloatField(default=0)),
                ("xg_proxy", models.FloatField(default=0)),
                ("xa_proxy", models.FloatField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_stats",
                        to="scout.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season")},
            },
        ),
    ]
