# Generated by Django 4.2.28 on 2026-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value_eur',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CDM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('FW', 'Forward')], max_length=10),
        ),
    ]
