# Generated by Django 4.2.28 on 2026-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scout", "0002_player_current_club_player_market_value_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
