# Generated by Django 4.2.28 on 2026-02-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("sprints", models.IntegerField(default=0)),
                ("accelerations", models.IntegerField(default=0)),
                (
                    "rpe",
                    models.FloatField(
                        blank=True,
                        help_text="Rate of Perceived Exertion 1-10",
                        null=True,
                    ),
                ),
                (
                    "sleep_quality",
                    models.IntegerField(
                        blank=True, help_text="Sleep quality 1-10", null=True
                    ),
                ),
                ("minutes_played", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_loads",
                        to="scout.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InjuryRiskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("horizon_days", models.IntegerField(default=7)),
                ("risk_probability", models.FloatField()),
                ("shap_factors", models.JSONField(default=list)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_predictions",
                        to="scout.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("injury_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        default="mild",
                        max_length=20,
                    ),
                ),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("matches_missed", models.PositiveIntegerField(default=0)),
                ("recurrence_flag", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="scout.player",
                    ),
                ),
            ],
        ),
    ]
