# Generated by Django 4.2.28 on 2026-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("physio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingload",
            name="sleep_quality",
            field=models.FloatField(
                blank=True, help_text="Sleep quality 1-10", null=True
            ),
        ),
    ]
