# Generated by Django 4.2.28 on 2026-02-19 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("physio", "0002_alter_trainingload_sleep_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=120, unique=True)),
                ("team", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["team", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalInjuryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("injury_start", models.DateField()),
                ("body_part", models.CharField(default="unknown", max_length=60)),
                ("severity", models.CharField(default="minor", max_length=20)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injury_events",
                        to="physio.globalplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["player", "injury_start"],
            },
        ),
        migrations.CreateModel(
            name="GlobalDailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("acwr", models.FloatField(blank=True, null=True)),
                ("atl", models.FloatField(blank=True, null=True)),
                ("ctl28", models.FloatField(blank=True, null=True)),
                ("ctl42", models.FloatField(blank=True, null=True)),
                ("daily_load", models.FloatField(blank=True, null=True)),
                ("monotony", models.FloatField(blank=True, null=True)),
                ("strain", models.FloatField(blank=True, null=True)),
                ("weekly_load", models.FloatField(blank=True, null=True)),
                ("fatigue", models.FloatField(blank=True, null=True)),
                ("mood", models.FloatField(blank=True, null=True)),
                ("readiness", models.FloatField(blank=True, null=True)),
                ("sleep_duration", models.FloatField(blank=True, null=True)),
                ("sleep_quality", models.FloatField(blank=True, null=True)),
                ("soreness", models.FloatField(blank=True, null=True)),
                ("stress", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="physio.globalplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["player", "date"],
                "unique_together": {("player", "date")},
            },
        ),
    ]
