# Generated by Django 4.2.28 on 2026-02-28 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scout", "0002_player_current_club_player_market_value_eur_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("physio", "0003_global_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryriskprediction",
            name="confidence_band",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="data_quality_score",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="flag_for_physio_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="model_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="monitoring_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="recommended_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="risk_band",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="sufficient_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="injuryriskprediction",
            name="top_factor",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="FlagAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flagged_date", models.DateField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag_acknowledgments",
                        to="scout.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-flagged_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("injury_created", "Injury Created"),
                            ("injury_updated", "Injury Updated"),
                            ("injury_deleted", "Injury Deleted"),
                            ("load_created", "Training Load Created"),
                            ("load_deleted", "Training Load Deleted"),
                            ("prediction_requested", "Prediction Requested"),
                            ("flag_acknowledged", "Flag Acknowledged"),
                            ("csv_import", "CSV Import"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("detail", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physio_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
