# Generated by Django 4.2.28 on 2026-03-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("physio", "0004_injuryriskprediction_confidence_band_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingload",
            name="readiness",
            field=models.FloatField(blank=True, help_text="Readiness 1-10", null=True),
        ),
        migrations.AddField(
            model_name="trainingload",
            name="soreness",
            field=models.FloatField(
                blank=True, help_text="Muscle Soreness 1-10", null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("injury_created", "Injury Created"),
                    ("injury_updated", "Injury Updated"),
                    ("injury_deleted", "Injury Deleted"),
                    ("load_created", "Training Load Created"),
                    ("load_deleted", "Training Load Deleted"),
                    ("prediction_requested", "Prediction Requested"),
                    ("flag_acknowledged", "Flag Acknowledged"),
                    ("csv_import", "CSV Import"),
                    ("simulation_run", "Simulation Run"),
                ],
                max_length=30,
            ),
        ),
    ]
