# Generated by Django 4.2.28 on 2026-03-20 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scout", "0003_player_phone"),
        ("physio", "0005_trainingload_readiness_trainingload_soreness_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysioAbsencePredictionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("age", models.PositiveSmallIntegerField(default=25)),
                ("position", models.CharField(blank=True, default="", max_length=60)),
                ("injury_type", models.CharField(max_length=80)),
                (
                    "context",
                    models.CharField(default="training session", max_length=80),
                ),
                ("previous_same_zone", models.PositiveSmallIntegerField(default=0)),
                ("recurrence_same_zone", models.BooleanField(default=False)),
                ("severity_score", models.FloatField(default=0.0)),
                (
                    "severity_class",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "confidence_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("absence_days_min", models.PositiveSmallIntegerField(default=0)),
                ("absence_days_max", models.PositiveSmallIntegerField(default=0)),
                (
                    "absence_weeks_label",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("immediate_actions", models.JSONField(blank=True, default=dict)),
                ("similar_cases_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scout.player",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysioHistoricalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=120)),
                ("age", models.PositiveSmallIntegerField()),
                ("position", models.CharField(max_length=60)),
                ("injury_type", models.CharField(max_length=80)),
                ("primary_zone", models.CharField(max_length=80)),
                ("context", models.CharField(default="training", max_length=80)),
                ("previous_injuries", models.PositiveSmallIntegerField(default=0)),
                ("previous_same_zone", models.PositiveSmallIntegerField(default=0)),
                ("recurrence_same_zone", models.BooleanField(default=False)),
                (
                    "training_load_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "days_since_last_intense",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("absence_days", models.PositiveSmallIntegerField(default=0)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "outcome_label",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysioRiskSimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("position", models.CharField(max_length=60)),
                ("previous_injuries", models.PositiveSmallIntegerField(default=0)),
                (
                    "injuries_last_2_seasons",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("primary_zone", models.CharField(max_length=80)),
                (
                    "training_load_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "days_since_last_intense",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("risk_drivers", models.JSONField(blank=True, default=list)),
                ("recommendation_blocks", models.JSONField(blank=True, default=dict)),
                ("similar_profiles_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scout.player",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysioSimilarityMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("squad_daily_risk", "Squad Daily Risk"),
                            ("player_risk_simulator", "Player Risk Simulator"),
                            ("absence_prediction", "Absence Prediction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("distance", models.FloatField(default=0.0)),
                ("match_pct", models.FloatField(default=0.0)),
                ("summary", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absence_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="physio.physioabsencepredictionrun",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_in",
                        to="physio.physiohistoricalcase",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="physio.physiorisksimulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="PhysioAIExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("squad_daily_risk", "Squad Daily Risk"),
                            ("player_risk_simulator", "Player Risk Simulator"),
                            ("absence_prediction", "Absence Prediction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_text", models.TextField(blank=True, default="")),
                ("provider", models.CharField(default="fallback", max_length=30)),
                ("fallback_used", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absence_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="physio.physioabsencepredictionrun",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="physio.physiorisksimulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysioSquadSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("previous_injuries", models.PositiveSmallIntegerField(default=0)),
                (
                    "primary_zone",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "training_load_band",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "days_since_last_intense",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("top_drivers", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physio_squad_snapshots",
                        to="scout.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-risk_score"],
                "unique_together": {("player", "snapshot_date")},
            },
        ),
    ]
